# Generated by Django 5.0 on 2024-02-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_borrow_transaction'),
        ('transactions', '0006_remove_transaction_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
