# Generated by Django 5.0 on 2024-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
