# Generated by Django 5.0 on 2024-02-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_alter_book_image_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='car',
            new_name='book',
        ),
    ]
