# Generated by Django 5.0 on 2024-02-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_borrow_transaction_alter_borrow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='transaction',
        ),
    ]
