# Generated by Django 5.0 on 2024-02-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_borrow_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
