# Generated by Django 5.0 on 2024-02-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibraryaccount',
            old_name='balace',
            new_name='balance',
        ),
    ]
